name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"          # Runs once every day
  workflow_dispatch:              # Allows manual run

permissions:
  contents: write                 # REQUIRED to commit the SVG

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Abhay-coding
          outputs: dist/snake.svg, dist/snake-dark.svg

      - name: Push snake.svg
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist/*.svg'
          message: 'Generated contribution snake'
